/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFormulationsRouteImport } from './routes/_authenticated/formulations'
import { Route as AuthenticatedQuoteNewRouteImport } from './routes/_authenticated/quote.new'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminImportRouteImport } from './routes/_authenticated/admin.import'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormulationsRoute = AuthenticatedFormulationsRouteImport.update({
  id: '/formulations',
  path: '/formulations',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuoteNewRoute = AuthenticatedQuoteNewRouteImport.update({
  id: '/quote/new',
  path: '/quote/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminProductsRoute = AuthenticatedAdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminImportRoute = AuthenticatedAdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/formulations': typeof AuthenticatedFormulationsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/quote/new': typeof AuthenticatedQuoteNewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/formulations': typeof AuthenticatedFormulationsRoute
  '/admin/import': typeof AuthenticatedAdminImportRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/quote/new': typeof AuthenticatedQuoteNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/formulations': typeof AuthenticatedFormulationsRoute
  '/_authenticated/admin/import': typeof AuthenticatedAdminImportRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/quote/new': typeof AuthenticatedQuoteNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/'
    | '/formulations'
    | '/admin/import'
    | '/admin/products'
    | '/quote/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/' | '/formulations' | '/admin/import' | '/admin/products' | '/quote/new'
  id:
    | '__root__'
    | '/auth'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/formulations'
    | '/_authenticated/admin/import'
    | '/_authenticated/admin/products'
    | '/_authenticated/quote/new'
  fileRoutesById: FileRoutesById
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFormulationsRoute: typeof AuthenticatedFormulationsRoute
  AuthenticatedAdminImportRoute: typeof AuthenticatedAdminImportRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedQuoteNewRoute: typeof AuthenticatedQuoteNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFormulationsRoute: AuthenticatedFormulationsRoute,
  AuthenticatedAdminImportRoute: AuthenticatedAdminImportRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedQuoteNewRoute: AuthenticatedQuoteNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface RootRouteChildren {
  AuthRoute: typeof AuthRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formulations': {
      id: '/_authenticated/formulations'
      path: '/formulations'
      fullPath: '/formulations'
      preLoaderRoute: typeof AuthenticatedFormulationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quote/new': {
      id: '/_authenticated/quote/new'
      path: '/quote/new'
      fullPath: '/quote/new'
      preLoaderRoute: typeof AuthenticatedQuoteNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/import': {
      id: '/_authenticated/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthenticatedAdminImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
